### ISSUE TITLE
`omc` v3.x does not work with cluster-scoped-resources in pipelines must-gather

### ISSUE THREAD

**Issue by gmeghnag** [gmeghnag/omc#109]
```
omc get tektonconfigs 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1a0 pc=0x26f6b57]

goroutine 1 [running]:
github.com/gmeghnag/omc/pkg/tablegenerator.GenerateCustomResourceTable({0x0})
	/home/runner/work/omc/omc/pkg/tablegenerator/tablegenerator.go:126 +0xb37
github.com/gmeghnag/omc/cmd/get.handleObject({0x0})
	/home/runner/work/omc/omc/cmd/get/get.go:407 +0x1092
github.com/gmeghnag/omc/cmd/get.getClusterScopedResources({0xc0009a3b60, 0xd}, {0xc000530be8, 0x13}, 0xc000936cf0)
	/home/runner/work/omc/omc/cmd/get/get.go:333 +0x5f2
github.com/gmeghnag/omc/cmd/get.glob..func1(0x46d9940?, {0xc0007d22f0?, 0x1?, 0x1?})
	/home/runner/work/omc/omc/cmd/get/get.go:107 +0x4bb
github.com/spf13/cobra.(*Command).execute(0x46d9940, {0xc0007d22b0, 0x1, 0x1})
	/home/runner/work/omc/omc/vendor/github.com/spf13/cobra/command.go:920 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0x46dad60)
	/home/runner/work/omc/omc/vendor/github.com/spf13/cobra/command.go:1040 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/work/omc/omc/vendor/github.com/spf13/cobra/command.go:968
main.main()
	/home/runner/work/omc/omc/main.go:24 +0x25
```

**Comment by gmeghnag** [comment]
Need to modify [openshift-pipelines must-gather](https://github.com/openshift-pipelines/must-gather) to fix the issue:
- cluster scoped resources should not be of type `List`, but there should be one yaml file for each resource;
- [`describe`](https://github.com/openshift-pipelines/must-gather/blob/main/bin/gather_pipelines#L21) folder should not exist.
