### ISSUE TITLE
`omc get clusteranalysistemplates.argoproj.io -A` command returns `runtime error: invalid memory address or nil pointer dereference`

### ISSUE THREAD

**Issue by gmeghnag** [gmeghnag/omc#146]
```
$ omc get clusteranalysistemplates.argoproj.io -A
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x198 pc=0x281f3a8]

goroutine 1 [running]:
github.com/gmeghnag/omc/pkg/tablegenerator.GenerateCustomResourceTable({0xc00188b350})
	/home/runner/work/omc/omc/pkg/tablegenerator/tablegenerator.go:169 +0xb28
github.com/gmeghnag/omc/cmd/get.handleObject({0xc00188b350})
	/home/runner/work/omc/omc/cmd/get/get.go:418 +0x1193
github.com/gmeghnag/omc/cmd/get.getClusterScopedResources({0xc0012d63d8, 0x18}, {0xc000e90704, 0xb}, 0xc001cd3e30)
	/home/runner/work/omc/omc/cmd/get/get.go:337 +0x5dd
github.com/gmeghnag/omc/cmd/get.glob..func1(0xc000215200?, {0xc00089e740?, 0x4?, 0x32b7776?})
	/home/runner/work/omc/omc/cmd/get/get.go:108 +0x49b
github.com/spf13/cobra.(*Command).execute(0x4ec0420, {0xc00089e720, 0x2, 0x2})
	/home/runner/work/omc/omc/vendor/github.com/spf13/cobra/command.go:944 +0x863
github.com/spf13/cobra.(*Command).ExecuteC(0x4ebd900)
	/home/runner/work/omc/omc/vendor/github.com/spf13/cobra/command.go:1068 +0x3a5
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/work/omc/omc/vendor/github.com/spf13/cobra/command.go:992
main.main()
	/home/runner/work/omc/omc/main.go:24 +0x1a
```

[gitops-must-gather.tar.gz](https://github.com/gmeghnag/omc/files/14917222/gitops-must-gather.tar.gz)

**Comment by gmeghnag** [comment]
The must-gather was incorrectly collected; the `clusteranalysistemplates` cluster-scoped resources were not collected as a single resource per file but as a `UnstructuredList` resource in a single file, so it caused the error, as `omc` was expecting a `Unstructured`while it found an `UnstructuredList`.

TODO: Menage the exception by printing an error message instead of the error stack trace.
