### ISSUE TITLE
No support for machines

### ISSUE THREAD

**Issue by cpassare** [gmeghnag/omc#23]
```
$ omc get machines -n openshift-machine-api
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x2430f94]

goroutine 1 [running]:
github.com/gmeghnag/omc/cmd/get/openshift/machine.getMachines({0xc00005eb40, 0x30}, {0x7ffe8311c8f4, 0x1}, {0x0, 0x0}, 0x0, {0x0, 0x0}, 0x0, ...)
	/home/runner/work/omc/omc/cmd/get/openshift/machine/machines.go:107 +0x11f4
github.com/gmeghnag/omc/cmd/get/openshift/machine.glob..func1(0x3cb09a0, {0xc0003809a0, 0x2, 0x2})
	/home/runner/work/omc/omc/cmd/get/openshift/machine/machines.go:205 +0xb6
github.com/spf13/cobra.(*Command).execute(0x3cb09a0, {0xc000380980, 0x2, 0x2})
	/home/runner/work/omc/omc/vendor/github.com/spf13/cobra/command.go:860 +0x5f8
github.com/spf13/cobra.(*Command).ExecuteC(0x3cb22a0)
	/home/runner/work/omc/omc/vendor/github.com/spf13/cobra/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/work/omc/omc/vendor/github.com/spf13/cobra/command.go:902
main.main()
	/home/runner/work/omc/omc/main.go:24 +0x25
```

**Comment by cpassare** [comment]
$ ls -l inspect.local.6895711748658304169/namespaces/openshift-machine-api/machine.openshift.io/machines/
total 40
-rwxr-xr-x. 1 cpassare cpassare 4267 Dec 13 12:52 sharedocp47-sfvj8-master-0.yaml
-rwxr-xr-x. 1 cpassare cpassare 3876 Dec 13 12:52 sharedocp47-sfvj8-master-1.yaml
-rwxr-xr-x. 1 cpassare cpassare 3877 Dec 13 12:52 sharedocp47-sfvj8-master-2.yaml
-rwxr-xr-x. 1 cpassare cpassare 5029 Dec 13 12:52 sharedocp47-sfvj8-worker-47kmv.yaml
-rwxr-xr-x. 1 cpassare cpassare 5077 Dec 13 12:52 sharedocp47-sfvj8-worker-x297s.yaml
-rwxr-xr-x. 1 cpassare cpassare 5030 Dec 13 12:52 sharedocp47-sfvj8-worker-zsz6l.yaml
